// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ChatbotDbContext))]
    partial class ChatbotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.BenchmarkResult", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultID"));

                    b.Property<double?>("AnswerRelevance")
                        .HasColumnType("float");

                    b.Property<int>("ConfigID")
                        .HasColumnType("int");

                    b.Property<double?>("ContextPrecision")
                        .HasColumnType("float");

                    b.Property<double?>("ContextRecall")
                        .HasColumnType("float");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Faithfulness")
                        .HasColumnType("float");

                    b.Property<string>("ModelResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("ResultID");

                    b.HasIndex("ConfigID");

                    b.HasIndex("QuestionID");

                    b.ToTable("BenchmarkResults");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID");

                    b.HasIndex("SessionID");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionID");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSizeKB")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentChunk", b =>
                {
                    b.Property<int>("ChunkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChunkID"));

                    b.Property<string>("ChunkContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<string>("Embedding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.HasKey("ChunkID");

                    b.HasIndex("DocumentID");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ExperimentConfig", b =>
                {
                    b.Property<int>("ConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigID"));

                    b.Property<string>("ApproachType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ChunkOverlap")
                        .HasColumnType("int");

                    b.Property<int?>("ChunkSize")
                        .HasColumnType("int");

                    b.Property<string>("ChunkingStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfigID");

                    b.ToTable("ExperimentConfigs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.MessageSource", b =>
                {
                    b.Property<int>("SourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceID"));

                    b.Property<int>("ChunkID")
                        .HasColumnType("int");

                    b.Property<int>("MessageID")
                        .HasColumnType("int");

                    b.Property<double?>("RelevanceScore")
                        .HasColumnType("float");

                    b.HasKey("SourceID");

                    b.HasIndex("ChunkID");

                    b.HasIndex("MessageID");

                    b.ToTable("MessageSources");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TestQuestion", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroundTruth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("SubjectID");

                    b.ToTable("TestQuestions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.BenchmarkResult", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ExperimentConfig", "ExperimentConfig")
                        .WithMany("BenchmarkResults")
                        .HasForeignKey("ConfigID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.TestQuestion", "TestQuestion")
                        .WithMany("BenchmarkResults")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExperimentConfig");

                    b.Navigation("TestQuestion");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatMessage", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ChatSession", "ChatSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Document", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany("Documents")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentChunk", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Document", "Document")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.MessageSource", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.DocumentChunk", "DocumentChunk")
                        .WithMany("MessageSources")
                        .HasForeignKey("ChunkID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.ChatMessage", "ChatMessage")
                        .WithMany("MessageSources")
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMessage");

                    b.Navigation("DocumentChunk");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TestQuestion", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany("TestQuestions")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatMessage", b =>
                {
                    b.Navigation("MessageSources");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Document", b =>
                {
                    b.Navigation("DocumentChunks");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentChunk", b =>
                {
                    b.Navigation("MessageSources");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ExperimentConfig", b =>
                {
                    b.Navigation("BenchmarkResults");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Subject", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("TestQuestions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TestQuestion", b =>
                {
                    b.Navigation("BenchmarkResults");
                });
#pragma warning restore 612, 618
        }
    }
}
